include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Các quy tắc chặt chẽ (strict lints) giúp code base sạch và thống nhất
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_empty_else: true
    cancel_subscriptions: true
    unnecessary_new: true
    unnecessary_this: true
    unrelated_type_equality_checks: true
